### ISSUE TITLE
Is this Demo of confluent supported http-sink-connector?

### ISSUE THREAD

**Issue by aggarwalb** [guptais/demo-http-sink-kafka-connector#1]
Hi Isha,
I was going through one of the post which you have mentioned regarding this and then I came here. So the first question I want to ask is Is this Demo of confluent supported http-sink-connector?

Secondly, Do you know by any chance if we can customize the http-sink-connector?

**Comment by guptais** [comment]
Hi @aggarwalb, thanks for your question. Yes it the demo of confluent supported http-sink connector. 

Regarding customising the connector, since it's a commercial connector, code might not be open source.
